name: Deploy Blog

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Target Version (例: 0.0.1)'
        required: true

jobs:
  build-and-publish:
    name: Build and upload
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        node-version: ['18']

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci .

      - name: Build
        run: npm run --prefix apps/blog build
        env:
          SPACE_ID: ${{ secrets.SPACE_ID }}
          DELIVERY_KEY: ${{ secrets.DELIVERY_KEY }}
          ENTRY_ID: ${{ secrets.ENTRY_ID }}
          NOTION_ACCESS_TOKEN: ${{ secrets.NOTION_ACCESS_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_DATABASE_VIEW_ID: ${{ secrets.NOTION_DATABASE_VIEW_ID }}
          NOTION_RNX_AUTH_TOKEN: ${{ secrets.NOTION_RNX_AUTH_TOKEN }}
          NOTION_RNX_ACTIVE_USER: ${{ secrets.NOTION_RNX_ACTIVE_USER }}

      - name: Export
        run: npm run --prefix apps/blog export

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog
          directory: ./apps/blog/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
